modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mixins]]
config = "reloadonlyrecipes.mixins.json"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

# KubeJS 为软依赖：可选、若安装则加载顺序在本 mod 之前
[[dependencies.${id}]]
modId = "kubejs"
type = "optional"
ordering = "AFTER"
side = "BOTH"
